<a href="https://colab.research.google.com/github/Domingo1987/Curso-Python/blob/main/3_7_Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introducción a las matrices en NumPy

Hasta ahora, hemos trabajado con lo que podríamos llamar "arreglos" en Python usando listas, una funcionalidad nativa del lenguaje. Pero hemos mencionado también que Python, en su forma estándar, no tiene un verdadero soporte para "arreglos" como lo conocemos en otros lenguajes de programación. Y sí, eso es cierto.

Pero aquí es donde NumPy entra en juego. NumPy es una biblioteca de Python que nos proporciona una estructura de datos tipo arreglo, el `ndarray`, optimizada para cálculos numéricos eficientes. En este módulo, vamos a aprender cómo trabajar con estos "arreglos" utilizando NumPy. Esta habilidad es esencial para muchas áreas en ciencia de datos, aprendizaje automático y computación científica, ya que nos permitirá manejar y realizar operaciones con conjuntos de datos numéricos de manera eficiente.

# Creación de matrices en NumPy

Podemos crear matrices en NumPy de varias formas. Aquí hay algunos ejemplos:

In [2]:
import numpy as np

# Crear una matriz a partir de una lista de listas
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("A =\n", A)

# Crear una matriz de ceros
B = np.zeros((3, 3))
print("\nB =\n", B)

# Crear una matriz de unos
C = np.ones((3, 3))
print("\nC =\n", C)

# Crear una matriz con valores aleatorios
D = np.random.rand(3, 3)
print("\nD =\n", D)

A =
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

B =
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

C =
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

D =
 [[0.10006265 0.46459809 0.83387496]
 [0.57198245 0.14696762 0.26891065]
 [0.05126992 0.73170849 0.54119233]]


Seguramente habrás notado en algún desafío anterior el uso de as en líneas de código como import libreria as lib. as en Python se utiliza para crear un alias durante la importación de un módulo. En este caso, estamos importando el módulo numpy y asignándole el alias np. Esto se hace por conveniencia para hacer el código más legible y conciso.

Después de esto, puedes usar el prefijo np. en lugar de numpy. para llamar a las funciones y métodos del módulo numpy. Esto es especialmente útil para módulos con nombres largos o que se utilizan con frecuencia.

El alias np para numpy es una convención ampliamente adoptada por la comunidad de Python, especialmente entre los científicos de datos, ingenieros y desarrolladores que utilizan numpy para el cálculo numérico. Utilizar estas convenciones ayuda a mantener el código coherente y fácil de leer entre diferentes proyectos y equipos. Sin embargo, podrías elegir cualquier nombre que desees para el alias. Por ejemplo, import numpy as nump también sería válido, pero no es comúnmente utilizado.

_Nota_: Puede ocurrir que Python no tenga NumPy en tu instalacion, lo resuelves con pip install numpy o similar según tu sistema.

# Acceso y modificación de elementos de la matriz

Podemos acceder y modificar elementos de la matriz utilizando índices. Veamos algunos ejemplos:

In [2]:
# Acceder a un elemento
print("A[0, 0] =", A[0, 0])

# Modificar un elemento
A[0, 0] = 10
print("\nA =\n", A)

A[0, 0] = 1

A =
 [[10  2  3]
 [ 4  5  6]
 [ 7  8  9]]


# Operaciones básicas con matrices

NumPy nos permite realizar varias operaciones con matrices, como suma, resta, producto escalar, producto de matrices y división. Veamos cómo hacerlo:

In [ ]:
# Crear dos matrices para las operaciones
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Suma de matrices
print("A + B =\n", A + B)

# Resta de matrices
print("\nA - B =\n", A - B)

# Producto escalar
print("\n2 * A =\n", 2 * A)

# Producto de matrices
print("\nA @ B =\n", A @ B)

# División de matrices
print("\nA / B =\n", A / B)

# Algunas operaciones especiales con matrices

Además de las operaciones básicas, NumPy también nos permite realizar algunas operaciones especiales con matrices, como transposición, determinante, inversa, traza y rango. Veamos cómo hacerlo:

In [3]:
# Transposición de una matriz
print("A.T =\n", A.T)

# Determinante de una matriz
print("\nnp.linalg.det(A) =", np.linalg.det(A))

# Inversa de una matriz
print("\nnp.linalg.inv(A) =\n", np.linalg.inv(A))

# Traza de una matriz
print("\nnp.trace(A) =", np.trace(A))

# Rango de una matriz
print("\nnp.linalg.matrix_rank(A) =", np.linalg.matrix_rank(A))

A.T =
 [[10  4  7]
 [ 2  5  8]
 [ 3  6  9]]

np.linalg.det(A) = -27.0

np.linalg.inv(A) =
 [[ 0.11111111 -0.22222222  0.11111111]
 [-0.22222222 -2.55555556  1.77777778]
 [ 0.11111111  2.44444444 -1.55555556]]

np.trace(A) = 24

np.linalg.matrix_rank(A) = 3


# Desafío 1

Considere las matrices \( A \) y \( B \) definidas como:

\[ A = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix} \]

y

\[ B = \begin{bmatrix} 5 & 6 \\ 7 & 8 \end{bmatrix} \]

Tu tarea es calcular la matriz resultante de la operación \( (2A + B^T) \). Recuerda que \( B^T \) denota la transposición de la matriz \( B \).

In [13]:
# @title SOLUCIÓN
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
result = (2 * A + B.T)
result

array([[ 7, 11],
       [12, 16]])

# Desafío 2

Dada la matriz \( A = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 9 \end{bmatrix} \), encuentra la traza de la matriz inversa de \( A \).

In [10]:
# @title SOLUCIÓN
A = np.array([[1, 0, 1], [4, -1, 4], [5, 6, 7]])
trace_inv_A = np.trace(np.linalg.inv(A))
trace_inv_A


15.00000000000002

# Desafío 3

Dada la matriz \( A = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 9 \end{bmatrix} \), encuentra el rango de la matriz resultante de \( (A + A^T) \).

In [11]:
# @title SOLUCIÓN
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
rank_result = np.linalg.matrix_rank(A + A.T)
rank_result

2

# Desafío de Batalla Naval

Para este desafío, tendrás que implementar un juego sencillo de "Batalla Naval". El tablero de juego será una matriz de 5x5 donde el agua será representada por ceros (0) y los barcos por unos (1).

Primero, crea un tablero de juego utilizando NumPy, que será una matriz de ceros de 5x5.

Luego, coloca tres barcos en el tablero de juego. Cada barco es un 1 y debes colocarlo en una posición aleatoria en el tablero. No te preocupes por el tamaño de los barcos; cada barco ocupará solo una celda.

Finalmente, crea una función que acepte dos argumentos (las coordenadas x, y), y que verifique si en esa posición hay un barco (1) o agua (0). La función debe imprimir un mensaje indicando si se golpeó un barco o si el disparo cayó al agua.

In [23]:
# @title Solución
import numpy as np

# Crear un tablero de juego 5x5


# Colocar tres barcos en posiciones aleatorias

    #x, y = np.random.randint(0, 5, size=2)


# Función para verificar si hay un barco o agua en las coordenadas dadas


# Prueba la función con algunas coordenadas

